# Generated by Django 3.0.3 on 2021-07-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
