# Generated by Django 3.0.3 on 2021-08-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[(1, 'Available'), (2, 'Do Not Disturb'), (3, 'Asleep')], default=1, max_length=32),
        ),
    ]
