# Generated by Django 3.0.3 on 2021-08-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_profile_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='userdata.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(blank=True, to='userdata.Profile'),
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Profile')),
            ],
        ),
    ]
