# Generated by Django 3.0.3 on 2021-08-23 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0010_auto_20210823_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
