# Generated by Django 3.0.3 on 2021-08-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0011_status_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='userdata.Profile'),
        ),
    ]
