# Generated by Django 5.0.6 on 2024-07-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0012_auto_20210827_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='userdata.profile'),
        ),
    ]
